name: dbt pipeline

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 7 * * *"   # daily at 07:00 UTC

  workflow_dispatch:

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          pip install dbt-bigquery

      - name: Create GCP credentials file
        env:
          BIGQUERY_KEY: ${{ secrets.BIGQUERY_KEY }}
        run: |
          echo "$BIGQUERY_KEY" > /tmp/keyfile.json

      # ✅ ESTE ES EL BLOQUE CLAVE QUE TE FALLABA
      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          saas_dbt:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: service-account
                project: dtc-data-engineering-496009
                dataset: saas_analytics
                threads: 1
                keyfile: /tmp/keyfile.json
          EOF

      - name: Run dbt pipeline
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/keyfile.json
        run: |
          cd saas_dbt
          dbt deps
          dbt run
          dbt test