name: dbt pipeline

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  run-dbt:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          pip install dbt-bigquery

      - name: Create GCP credentials file
        env:
          BIGQUERY_KEY: ${{ secrets.BIGQUERY_KEY }}
        run: |
          echo "$BIGQUERY_KEY" > /tmp/keyfile.json

      # ✅ Crear profile desde TEMPLATE (CLAVE)
      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          cat saas_dbt/profiles.yml.template > ~/.dbt/profiles.yml

      # ✅ DEBUG (MUY IMPORTANTE TEMPORAL)
      - name: Debug dbt profile
        run: |
          echo "==== profiles.yml ===="
          cat ~/.dbt/profiles.yml

      # ✅ DEBUG CONFIG REAL DE DBT (CLAVE)
      - name: Debug dbt config
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/keyfile.json
        run: |
          cd saas_dbt
          dbt debug

      - name: Run dbt pipeline
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/keyfile.json
        run: |
          cd saas_dbt
          dbt deps
          dbt build --target dev